# -*- coding: utf-8 -*-
"""Predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L2Bu1GNGBywRtL5bk3FO__1lGSF-HYA_
"""

import os
import librosa
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import load_model

# Load the trained model
model_path = ''
loaded_model = load_model(model_path)

def predict_audio_category(model, audio_data, max_length):
    # Ekstraksi fitur audio (misalnya, MFCC)
    mfccs = librosa.feature.mfcc(y=audio_data, sr=sr, n_mfcc=13)

    # Zero-padding untuk menyamakan panjang fitur
    if mfccs.shape[1] < max_length:
        pad_width = max_length - mfccs.shape[1]
        mfccs = np.pad(mfccs, pad_width=((0, 0), (0, pad_width)), mode='constant')
    else:
        mfccs = mfccs[:, :max_length]

    # Konversi data ke bentuk array NumPy
    mfccs = np.array([mfccs])

    # Melakukan prediksi menggunakan model
    predictions = model.predict(mfccs)

    # Mendapatkan indeks kelas dengan probabilitas tertinggi
    predicted_class_index = np.argmax(predictions)

    # Mendapatkan label kelas menggunakan label_encoder
    predicted_class_label = label_encoder.classes_[predicted_class_index]

    return predicted_class_label

predicted_label = predict_audio_category(loaded_model, audio_data, max_length)
print(f"Predicted Label: {predicted_label}")